<?php

namespace AppBundle\Repository;

/**
 * CalculationHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculationHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
