<?php

namespace AppBundle\Repository;

/**
 * paymentScheduleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentScheduleRepository extends \Doctrine\ORM\EntityRepository
{
}
